### PR TITLE
Add color text

### PR DESCRIPTION
**Pull request by tekknolagi**
I added some color text to the output. Makes it easier to quickly eyeball!

### CODE REVIEW

**Comment by zorgnax** [comment]
I like the idea, but not sure a compiled-in option is the best way to do it because once you color it, its not syntactically tap anymore. Maybe an extra program, tap_color that can filter the tap results or maybe my own version of prove which can color output this way. The perl version of prove comes with some form of color output, but doesn't do the ok/not ok statements.

Maybe instead of a macro, we could use an environment variable? TAP_COLOR could be an easy way to toggle it without having the global effect.

also maybe an exported function tap_color() that can set it on....

**Comment by tokenrove** [comment]
IMHO the whole point of TAP is that it can be read by any of these:
  https://testanything.org/consumers.html
and they can produce various pretty output.  For example, it looks like node-tap has more modern output than prove.  I would personally prefer to see libtap remain a minimal emitter of TAP.

**Comment by tekknolagi** [comment]
@tokenrove @zorgnax Does adding color necessarily mean that it cannot be consumed by those programs?

**Comment by tekknolagi** [comment]
@zorgnax would you like to add a tap_color function? Not sure how that would work, though, unless there was some sort of global state.

**Comment by zorgnax** [comment]
yeah, tap_color() could set a global variable. but actually I think its best to just use prove which will color the results:

    prove -v t/mytest

although when I use it, my diagnostic messages aren't always right after the ok/not ok statement it refers to. but hopefully they'll fix that someday.

Also I tried node-tap and really like the nyan cat test result format.

**Comment by tekknolagi** [comment]
@zorgnax So are you expecting another pull request or is this fine or...?

**Comment by zorgnax** [comment]
no pull requests necessary. prove -v's color output seems enough.

**Pull request merged**
